### ISSUE TITLE
loading... does not disappear

### ISSUE THREAD

**Issue by theo1012** [alexpopov86/blockchain_end_to_end#2]
I tried to realize your application repo on my laptop and failed. 
It keeps to show "loading...", and after some debug, I noticed this line has never been executed.

```
.once('receipt', (receipt) => {
this.setState({ loading: false })
})
```
Does your version work correctly?

**Comment by alexpopov86** [comment]
fixed, please use 'transactionHash' instead of 'receipt' in such case.
